name: status-notification

on:
  workflow_run:
    workflows: [web-ccms-api, web-ccms-selenium, web-external-api, workflow-beta, workflow-gnps, workflow-gnps-fast, workflow-proteomics3-fast]
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    env:
      TRIGGERING_WORKFLOW_NAME:  ${{ github.event.workflow_run.name }}
      TRIGGERING_WORKFLOW_ID:  ${{ github.event.workflow_run.id }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install smtplib
    - name: Test with nose2
      run: |
        pip install nose2
        cd status_notification && nose2 -v
