name: workflow-integration-proteomics3-fast

on:
  push:
    branches:
      - master
  schedule:
   - cron:  '10 * * * *'

jobs:
  workflow-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xmltodict
        pip install requests
        pip install pandas
    - name: Run Tests
      run: |
        python workflow_integration/submit_test_job_batch.py --credential_username ${{ secrets.CCMS_TESTUSER_USERNAME }} \
        --credential_password ${{ secrets.CCMS_TESTUSER_PASSWORD }} \
        --credential_server proteomics3.ucsd.edu \
        --workflow_task_file CCMSDeployments/fast_test_workflow/test-integration-workflow/test_tasks.tsv
