name: workflow-tools

on:
  pull_request:
    branches:
      master
  push:
    branches:
      master
  schedule:
    - cron:  '1 12 * * *'

jobs:
  workflow-tools-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with nose2
      run: |
        pip install nose2
        cd tool_integration && nose2 -v
