name: workflow-gnps

on:
  pull_request:
    types: [unlocked]
  schedule:
    - cron:  '1 12 * * *'

jobs:
  workflow-gnps-networking-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xmltodict requests pandas
    - name: Run Tests
      run: |
        python workflow_integration/submit_test_job_batch.py --credential_username ${{ secrets.CCMS_TESTUSER_USERNAME }} \
        --credential_password ${{ secrets.CCMS_TESTUSER_PASSWORD }} \
        --credential_server gnps.ucsd.edu \
        --workflow_task_file GNPS_Workflows/metabolomics-snets-v2/test-integration-workflow/test_tasks.csv

  workflow-gnps-fbmn-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xmltodict requests pandas
      - name: Run Tests
        run: |
          python workflow_integration/submit_test_job_batch.py --credential_username ${{ secrets.CCMS_TESTUSER_USERNAME }} \
          --credential_password ${{ secrets.CCMS_TESTUSER_PASSWORD }} \
          --credential_server gnps.ucsd.edu \
          --workflow_task_file GNPS_Workflows/feature-based-molecular-networking/test-integration-workflow/test_tasks.csv

  workflow-gnps-library-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xmltodict requests pandas
    - name: Run Tests
      run: |
        python workflow_integration/submit_test_job_batch.py --credential_username ${{ secrets.CCMS_TESTUSER_USERNAME }} \
        --credential_password ${{ secrets.CCMS_TESTUSER_PASSWORD }} \
        --credential_server gnps.ucsd.edu \
        --workflow_task_file GNPS_Workflows/molecular-librarysearch-v2/test-integration-workflow/test_tasks.csv
  
  workflow-gnps-masst-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xmltodict requests pandas
    - name: Run Tests
      run: |
        python workflow_integration/submit_test_job_batch.py --credential_username ${{ secrets.CCMS_TESTUSER_USERNAME }} \
        --credential_password ${{ secrets.CCMS_TESTUSER_PASSWORD }} \
        --credential_server gnps.ucsd.edu \
        --workflow_task_file GNPS_Workflows/search_single_spectrum/test-integration-workflow/test_tasks.csv

  # workflow-gnps-qemistree-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #     with:
  #       submodules: recursive
  #   - name: Set up Python 3.7
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: 3.7
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install xmltodict requests pandas
  #   - name: Run Tests
  #     run: |
  #       python workflow_integration/submit_test_job_batch.py --credential_username ${{ secrets.CCMS_TESTUSER_USERNAME }} \
  #       --credential_password ${{ secrets.CCMS_TESTUSER_PASSWORD }} \
  #       --credential_server gnps.ucsd.edu \
  #       --workflow_task_file GNPS_Workflows/qemistree/test-integration-workflow/test_tasks.csv

  workflow-gnps-gc-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xmltodict requests pandas
    - name: Run Tests
      run: |
        python workflow_integration/submit_test_job_batch.py --credential_username ${{ secrets.CCMS_TESTUSER_USERNAME }} \
        --credential_password ${{ secrets.CCMS_TESTUSER_PASSWORD }} \
        --credential_server gnps.ucsd.edu \
        --workflow_task_file GNPS_Workflows/mshub-gc/test-integration-workflow/test_tasks.csv

        python workflow_integration/submit_test_job_batch.py --credential_username ${{ secrets.CCMS_TESTUSER_USERNAME }} \
        --credential_password ${{ secrets.CCMS_TESTUSER_PASSWORD }} \
        --credential_server gnps.ucsd.edu \
        --workflow_task_file GNPS_Workflows/molecular-librarysearch-gc/test-integration-workflow/test_tasks.csv

  workflow-gnps-mergepolarity-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xmltodict requests pandas
    - name: Run Tests
      run: |
        python workflow_integration/submit_test_job_batch.py --credential_username ${{ secrets.CCMS_TESTUSER_USERNAME }} \
        --credential_password ${{ secrets.CCMS_TESTUSER_PASSWORD }} \
        --credential_server gnps.ucsd.edu \
        --workflow_task_file GNPS_Workflows/merge_networks_polarity/test-integration-workflow/test_tasks.csv

  workflow-gnps-molnet-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xmltodict requests pandas
    - name: Run Tests
      run: |
        python workflow_integration/submit_test_job_batch.py --credential_username ${{ secrets.CCMS_TESTUSER_USERNAME }} \
        --credential_password ${{ secrets.CCMS_TESTUSER_PASSWORD }} \
        --credential_server gnps.ucsd.edu \
        --workflow_task_file GNPS_Workflows/molnetenhancer/test-integration-workflow/test_tasks.csv

  workflow-gnps-ms2lda-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xmltodict requests pandas
    - name: Run Tests
      run: |
        python workflow_integration/submit_test_job_batch.py --credential_username ${{ secrets.CCMS_TESTUSER_USERNAME }} \
        --credential_password ${{ secrets.CCMS_TESTUSER_PASSWORD }} \
        --credential_server gnps.ucsd.edu \
        --workflow_task_file GNPS_Workflows/ms2lda_motifdb/test-integration-workflow/test_tasks.csv

  workflow-gnps-falcon-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xmltodict requests pandas
    - name: Run Tests
      run: |
        python workflow_integration/submit_test_job_batch.py --credential_username ${{ secrets.CCMS_TESTUSER_USERNAME }} \
        --credential_password ${{ secrets.CCMS_TESTUSER_PASSWORD }} \
        --credential_server gnps.ucsd.edu \
        --workflow_task_file GNPS_Workflows/FalconClusterWorkflow/proteosafe/falcon-cluster/test-integration-workflow/test_tasks.csv

  workflow-gnps-misc-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xmltodict requests pandas
    - name: Run Tests
      run: |
        python workflow_integration/submit_test_job_batch.py --credential_username ${{ secrets.CCMS_TESTUSER_USERNAME }} \
        --credential_password ${{ secrets.CCMS_TESTUSER_PASSWORD }} \
        --credential_server gnps.ucsd.edu \
        --workflow_task_file GNPS_Workflows/workflow-integration-misc-tests/test_tasks.csv